apiVersion: v1
kind: ConfigMap
metadata:
  name: apache2-html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Bienvenue</title>
    </head>
    <body>
      <h1>Hello Apache2 on Kubernetes!</h1>
    </body>
    </html>
